# Generated by Django 3.1.5 on 2021-01-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name': 'Customer', 'verbose_name_plural': '2. Customers'},
        ),
        migrations.AlterModelOptions(
            name='customertags',
            options={'ordering': ('name',), 'verbose_name': 'Customer Tag', 'verbose_name_plural': '1. Customer Tags'},
        ),
    ]
