# Generated by Django 3.1.5 on 2021-01-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Dispositions',
            },
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Interaction Type',
            },
        ),
        migrations.CreateModel(
            name='Subdisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('disposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.disposition')),
            ],
            options={
                'verbose_name_plural': '5. Subdispositions',
            },
        ),
        migrations.CreateModel(
            name='InteractionSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('interaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.interactiontype')),
            ],
            options={
                'verbose_name_plural': '3. Interaction Sub-Type',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('interaction_subtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.interactionsubtype')),
                ('subdisposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.subdisposition')),
            ],
            options={
                'verbose_name_plural': '1. Interactions',
            },
        ),
    ]
